config/routes.rb
Rails.application.routes.draw do
  get 'site/contacts'
  root to: 'site#home'
  get 'site/home'

  resources :riders
  resources :slogans
  resources :photos
  resources :location
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rider.rb
class Rider < ApplicationRecord
end

app/models/slogan.rb
class Slogan < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: EMAIL_FORMAT }, uniqueness: true
  validates :slogan, presence: true, length: { maximum: 50 }
  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  before_action :set_rider, only: [:show, :edit, :update, :destroy]

  # GET /riders
  # GET /riders.json
  def index
    @riders = Rider.all
  end

  # GET /riders/1
  # GET /riders/1.json
  def show
  end

  # GET /riders/new
  def new
    @rider = Rider.new
  end

  # GET /riders/1/edit
  def edit
  end

  # POST /riders
  # POST /riders.json
  def create
    @rider = Rider.new(rider_params)

    respond_to do |format|
      if @rider.save
        format.html { redirect_to @rider, notice: 'Rider was successfully created.' }
        format.json { render :show, status: :created, location: @rider }
      else
        format.html { render :new }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /riders/1
  # PATCH/PUT /riders/1.json
  def update
    respond_to do |format|
      if @rider.update(rider_params)
        format.html { redirect_to @rider, notice: 'Rider was successfully updated.' }
        format.json { render :show, status: :ok, location: @rider }
      else
        format.html { render :edit }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riders/1
  # DELETE /riders/1.json
  def destroy
    @rider.destroy
    respond_to do |format|
      format.html { redirect_to riders_url, notice: 'Rider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rider
      @rider = Rider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rider_params
      params.fetch(:rider, {})
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def contacts
  end
end

app/controllers/slogans_controller.rb
class SlogansController < ApplicationController
  before_action :set_slogan, only: [:show, :edit, :update, :destroy]

  # GET /slogans
  # GET /slogans.json
  def index
    @slogans = Slogan.all
  end

  # GET /slogans/1
  # GET /slogans/1.json
  def show
  end

  # GET /slogans/new
  def new
    @slogan = Slogan.new
  end

  # GET /slogans/1/edit
  def edit
  end

  # POST /slogans
  # POST /slogans.json
  def create
    @slogan = Slogan.new(slogan_params)

    respond_to do |format|
      if @slogan.save
        format.html { redirect_to @slogan, notice: 'Thank you for submitting your Slogan idea.' }
        format.json { render :show, status: :created, location: @slogan }
      else
        format.html { render :new }
        format.json { render json: @slogan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slogans/1
  # PATCH/PUT /slogans/1.json
  def update
    respond_to do |format|
      if @slogan.update(slogan_params)
        format.html { redirect_to @slogan, notice: 'Slogan was successfully updated.' }
        format.json { render :show, status: :ok, location: @slogan }
      else
        format.html { render :edit }
        format.json { render json: @slogan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slogans/1
  # DELETE /slogans/1.json
  def destroy
    @slogan.destroy
    respond_to do |format|
      format.html { redirect_to slogans_url, notice: 'Slogan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slogan
      @slogan = Slogan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slogan_params
      params.fetch(:slogan, {}).permit(:first_name, :last_name, :email, :slogan)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'logo.png' %>
  <title>BoulderBikeTour</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="initial-scale=1.0">
  <meta charset="utf-8">

  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<header>
  <div class="container">
    <div class="col-lg-4">
      <div class="logo">
        <a href="/site/home"><%= image_tag("logo1.png", :alt => "logo", :class => "logo-main") %></a>
      </div>
    </div>

    <div class="col-lg-8">
      <nav class="navbar navbar-default nb">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li><a href="/site/home">Home</a></li>
              <li><a href="/photos">Photos</a></li>
              <li><a href="/location">Locations</a></li>
              <li><a href="/riders">Riders</a></li>
              <li><a href="/slogans">Slogan contast</a></li>
              <li><a href="/site/contacts">Contacts</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</header>

<body>
  <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
  <div class="container jumbotron">
    <%= yield %>
  </div>
</body>

<script>
  // When the user scrolls down 20px from the top of the document, show the button
  window.onscroll = function() {scrollFunction()};

  function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
      document.getElementById("myBtn").style.display = "block";
    } else {
      document.getElementById("myBtn").style.display = "none";
    }
  }

  // When the user clicks on the button, scroll to the top of the document
  function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
</script>

</html>

app/views/location/index.html.erb
<h1>Riders location</h1>
<p>On the map you will see the riders location. Click on the marker to see the riders name.</p>

<div id="map"></div>
<script src='https://maps.googleapis.com/maps/api/js?key=API_KEY&callback=initMap'
async defer></script>

<script>
  function initMap() {
    var locations =[
    ['Dustin Green', 40.00, -105.35],
    ['Jason Finn', 39.95, -105.24],
    ['Howard Thompson', 40.06, -105.26],
    ['Maggie Lantz', 40.03, -105.23],
    ['Lawrence Duran', 40.04, -105.23],
    ['Irene Molina', 39.96, -105.22],
    ['Nancy Garner', 39.98, -105.21],
    ['Tara Taylor', 40.00, -105.25],
    ['Alejandro Smith', 40.02, -105.26],
    ['Tricia Renshaw', 40.02, -105.30],
    ['Travis Cook', 40.01, -105.20],
    ['Joan Brooks', 39.98, -105.24],
    ['Joseph Rodgers', 39.99, -105.25],
    ['Matthew Gregson', 40.01, -105.29],
    ['Katie Dunlap', 39.97, -105.27],
    ['Leo Howard', 39.97, -105.33],
    ['Maria Baisden', 40.00, -105.29],
    ['Sandy Townsend', 40.05, -105.30],
    ['Melinda Stephenson', 39.99, -105.31],
    ['Jason Nichols', 40.01, -105.32]

  ];
    // Create a map object and specify the DOM element
    // for display.
    var map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 40.02, lng: -105.26},
      zoom: 12
    });

    // Create a marker and set its position.
    var infowindow = new google.maps.InfoWindow();
    var marker, i;

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
  }

</script>

app/views/photos/index.html.erb
<h1>Flickr photos</h1>
<h2>#bikerace #BoulderBikeTour</h2>
<p>Scroll down to see some Flickr photos.</p>
<div class="photos"> </div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"   integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="   crossorigin="anonymous"></script>

<script>
  var api_key = "2f7b3ca61bf5bbdbbe5928eb5ce05f3c"
  var page = 1

  if ($(document).height() < 300) {
     alert('hi')
  }

  $(window).scroll(function() {
    if($(window).scrollTop() + $(window).height() > $(document).height()-100) {

      var xhr = $.get("https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=" + api_key + "&tags=bikerace%2C+BoulderBikeTour&per_page=40&page=" + page + "&format=json&nojsoncallback=1")

      xhr.done(function(data) { console.log("success got data", data.photos.photo);

      var photos = data.photos.photo

      for (let item of photos) {
        var farm = item.farm
        var server = item.server
        var id = item.id
        var secret = item.secret
        var title = item.title
        var url = `https://farm${farm}.staticflickr.com/${server}/${id}_${secret}.jpg`

        $(".photos").append(`<img src=${url} alt=${title}>`)
      }
    });

    page = page + 1

  }
});

</script>

app/views/riders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registered Riders</h1>

<tbody>
  <table class="center">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>City of origin</th>
      <th>State of origin</th>
    </tr>
    <% @riders.each do |rider| %>
    <tr>
      <td><%= rider.first_name %></td>
      <td><%= rider.last_name %></td>
      <td><%= rider.city %></td>
      <td><%= rider.state %></td>
    </tr>
    <% end %>
  </table>

</tbody>
<br>

app/views/site/contacts.html.erb
<div id="contacts">
<h1>Contacts</h1>
<p>Get in touch with as for any questions. If you want to register for the race you can send us an email or call.</p>
<div class="container text-center">
  <p>BoulderBikeTour</p>
  <p>New York, NY 10012, US</p>
  <p>info@gmail.com | + 01 234 567 88</p>
</div>
</div>

app/views/site/home.html.erb
<div id="home">
  <h1>BoulderBikeTour</h1>
  <h2>Date: April 1, 2020</h2>
  <h2>Where: Colorado at the foot of the Rocky Mountains</h2>
  <p>Road bicycle racing is the cycle sport discipline of road cycling, held on paved roads. Road racing is the most popular professional form of bicycle racing, in terms of numbers of competitors, events and spectators. The two most common competition formats are mass start events, where riders start simultaneously (though sometimes with a handicap) and race to set finish point; and time trials, where individual riders or teams race a course alone against the clock. Stage races or "tours" take multiple days, and consist of several mass-start or time-trial stages ridden consecutively.</p>

  <p>Professional racing has been most popular in Western Europe, centered historically on France, Spain, Italy and the Low Countries. Since the mid-1980s the sport has diversified with professional races now held on all continents of the globe. Semi-professional and amateur races are also held in many countries. The sport is governed by the Union Cycliste Internationale (UCI). As well as the UCI's annual World Championships for men and women, the biggest event is the Tour de France, a three-week race that can attract over 500,000 roadside supporters a day.</p>

  <div class="container countdown">
    <h2 id="head">BoulderBikeTour <br> Countdown:</h2>
    <ul>
      <li><span id="months"></span><hr class="w-100 clearfix d-md-none">months</li>
      <li><span id="days"></span><hr class="w-100 clearfix d-md-none">days</li>
      <li><span id="hours"></span><hr class="w-100 clearfix d-md-none">Hours</li>
      <li><span id="minutes"></span><hr class="w-100 clearfix d-md-none">Minutes</li>
      <li><span id="seconds"></span><hr class="w-100 clearfix d-md-none">Seconds</li>
    </ul>
  </div>

  <script>
    // Set the date we're counting down to
    var countDownDate = new Date("April 1, 2020 10:00:00").getTime();
    // Update the count down every 1 second
    var x = setInterval(function() {
      // Get todays date and time
      var now = new Date().getTime();
      // Find the distance between now and the count down date
      var distance = countDownDate - now;

      var days = Math.floor(distance / (1000 * 60 * 60 * 24));
      if (days > 30) {
        var months = Math.floor(days / 30);
        days = days % 30;
      } else {
        months = 0;
      }
      var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((distance % (1000 * 60)) / 1000);

      document.getElementById("days").innerHTML = days;
      document.getElementById("months").innerHTML = months;
      document.getElementById("hours").innerHTML = hours;
      document.getElementById("minutes").innerHTML = minutes;
      document.getElementById("seconds").innerHTML = seconds;

    }, 1000);
  </script>

</div>

app/views/slogans/_form.html.erb
<%= form_with(model: slogan, local: true) do |form| %>

<div class="actions">
  <div class="col-lg-2">
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name, placeholder: "John", :required => true %>
  </div>
  <div class="col-lg-2">
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name, placeholder: "Smith", :required => true %>
  </div>
  <div class="col-lg-3">
    <%= form.label :email %><br>
    <%= form.text_field :email, placeholder: "john.smith@example.com", :required => true %>
  </div>
  <div class="col-lg-5">
    <%= form.label :slogan %><br>
    <%= form.text_area :slogan, placeholder: "Write your slogan idea under 50 characters..", :rows => 6, :cols => 50, :required => true %>
  </div>
</div>

<% if slogan.errors.any? %>
<div id="error_explanation">
  <p><%= pluralize(slogan.errors.count, "error") %> prohibited this slogan from being saved:</p>
  <div><% slogan.errors.full_messages.each do |message| %>
    <p><%= message %></p>
    <% end %>
  </div>
</div>
<% end %>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/slogans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slogan contast</h1>
<div class="container row">
  <div class="col-lg-8">
    <h2>Win a new bicycle!!!</h2>
    <p>We need a new slogan for our BoulderBikeTour. So we ask YOU to help us!</p>
    <p>Submit here your slogan idea, first name, last name and email and you can win a brand new bicycle!</p>
  </div>
  <div class="col-lg-4">
    <%= image_tag("cut.jpg", :alt => "bicycle", :class => "bike") %>
  </div>
</div>
<br><button class="actions"><%= link_to 'Add a new slogan', new_slogan_path %></button>
<tbody>
  <table class="center">
    <tr>
      <th>Slogan</th>
      <th>Name</th>
    </tr>
    <% @slogans.each do |slogan| %>
    <tr>
      <td><%= slogan.slogan %></td>
      <td><%= slogan.first_name %></td>
    </tr>
    <% end %>
  </table>
</tbody>

app/views/slogans/new.html.erb
<h1>New Slogan</h1>
<p>You can add here your slogan idea.</p>
<p>Please fill out all the fields. The winner will receive an email within April 1, 2019.</p>

<%= render 'form', slogan: @slogan %>

<%= link_to 'Back', slogans_path %>

app/views/slogans/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', slogans_path %>